config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users
  resources :login

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= session[:current_user_id] &&
      User.find_by(id: session[:current_user_id])
  end

end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  def destroy
    @current_user = session[:current_user_id] = nil
    redirect_to root_path
  end

  def new
    @user = User.new
  end

  def create
    if user = User.find_by(:username => params[:user][:username]).try(:authenticate, params[:user][:password])
      session[:current_user_id] = user.id
      redirect_to root_url
    else
      @user = User.new
      flash.now[:error] = 'Username / password is invalid'
      render :new
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(allowed_parameters)
    if @user.save
      session[:current_user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def allowed_parameters
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TriviaNight</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse" role="navigation">
    <div class="navbar-header">
      <%= link_to 'Trivia Night!', root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div class="navbar-right">
        <% if current_user %>
          <p class="navbar-text">Welcome to Trivia Night, <%= current_user.username %></p>
          <%= link_to 'Log out', login_path(current_user), :method => :delete, class: "btn btn-default navbar-btn" %>
        <% else %>
          <%= link_to 'Log in', new_login_path , class: "btn btn-default navbar-btn" %>
          <%= link_to 'Sign up', new_user_path , class: "btn btn-default navbar-btn" %>
        <% end %>
      </div>
    </div>
  </nav>
  <% if flash %>
    <% flash.each do |name, msg| %>
      <% flash_class = "alert alert-danger" if name == "error" %>
      <%= content_tag :div, msg, class: flash_class %>
    <% end %>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/login/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for @user, {url: '/login', :method => 'post'} do |f| %>
      <div class="form-group">
        <%= f.label :username %>
        <%= f.text_field :username, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <%= f.submit 'Log in', class: "btn btn-primary"%>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for @user do |f| %>
      <div class="form-group">
        <%= f.label :email%>
        <%= f.text_field :email, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :username %>
        <%= f.text_field :username, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
        <%= f.submit 'Sign up', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>